seeds = [
    'Ed Sheeran',
    'Jason Mraz',
    'Adele',
    'Maroon 5',
    'Lana Del Rey',
    'Cold Play',
    'Imagine Dragon',
    'James Blunt',
    'BlackPink',
    'Katy Perry',
    'P!nk',
    'Travis',
    'Rihanna',
    'Dua Lipa',
    'Lady Gaga',
    'Taylor Swift',
    'Ariana Grande',
    'Billie Eilish',
    'Travis Scott',
    'One direction'
]