seeds = [
    "Ed Sheeran",
    "Jason Mraz",
    "Adele",
    "Maroon 5",
    "Lana Del Rey",
    "ColdPlay",
    "Imagine Dragons",
    "James Blunt",
    "BlackPink",
    "Katy Perry",
    "P!nk",
    "Jessie J",
    "Rihanna",
    "Dua Lipa",
    "Lady Gaga",
    "Taylor Swift",
    "Ariana Grande",
    "Billie Eilish",
    "Travis Scott",
    "One direction",
]
